# Generated by Django 5.1.3 on 2024-11-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
